name: Cleanup old workflow runs

on:
  schedule:
    # 每 3 小时触发一次（UTC 时间）
    - cron: '5 */3 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs older than 3 hours
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching workflow runs..."
          # 获取 workflow runs（最多 100 条，可分页扩展）
          runs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs?per_page=100" \
            | jq -r '.workflow_runs[] | select(.created_at < "'$(date -u -d "3 hours ago" +%Y-%m-%dT%H:%M:%SZ)'") | .id')

          if [ -z "$runs" ]; then
            echo "No runs to delete"
          else
            for run_id in $runs; do
              echo "Deleting workflow run $run_id"
              curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/$run_id"
            done
          fi
